### ISSUE TITLE
How to fix PyQt5 error

### ISSUE THREAD

**Issue by filebe777** [azizaltuntas/Camelishing#2]
/Desktop/Camelishing# python start.py
  File "start.py", line 1
SyntaxError: Non-ASCII character '\xc5' in file start.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
root@kali:~/Desktop/Camelishing# pip install PyQt5
Collecting PyQt5
  Could not find a version that satisfies the requirement PyQt5 (from versions: )
No matching distribution found for PyQt5
root@kali:~/Desktop/Camelishing# pip install PyQt
Collecting PyQt
  Could not find a version that satisfies the requirement PyQt (from versions: )
No matching distribution found for PyQt

**Comment by azizaltuntas** [comment]
Hello.
Note: Camelishing Windows Supported..

Solution:

`apt-get install python3-pyqt`

**Comment by cryptonic01** [comment]
merhbalar ben windows kullaniyorum butun requirmentleri yukledim hersey tamam fakat hala calistiramadim toolu 


> Traceback (most recent call last):
  File "start.py", line 4, in <module>
    from PyQt5.QtWidgets import QApplication , QMainWindow ,QFileDialog , QListWidget,QListWidgetItem ,QTreeWidgetItem ,QMessageBox,QLineEdit,QGraphicsPixmapItem
ImportError: No module named 'PyQt5'



bu hatayi aliyorum her defasinda pyqt5 kurdugum halde ? 


yardimci olabilirmisiniz ? 

-----------------------


Hi, I'm using windows but still having some problems with runing the tool, I'm using python 3.5 & python 3.4 and I have installed all the requirments all stuff but having I still can't run the tool.

could you help me please ? thanks.

**Comment by azizaltuntas** [comment]
cryptonic01 Merhaba. Kurulum yaparken kullandığın komutu ve komutu yazdıktan sonraki çıktıyı verebilir misin ?

**Comment by filebe777** [comment]
root@kali:~# apt-get install python3-pyqt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pyqt

**Comment by azizaltuntas** [comment]
Please try;

sudo apt-get install python3-pyqt5
sudo apt-get install qttools5-dev-tools
sudo apt-get install qtcreator pyqt5-dev-tools
pip3 install pyqt5

Note : It is better to setup in windows os..

**Comment by cryptonic01** [comment]
@azizaltuntas  Kullandığım komut sizin vermiş olduğunuz powershell komudu.

> pip install -r requirements.txt
![astra](https://user-images.githubusercontent.com/37256165/43087506-e537fffc-8e54-11e8-977f-673bc8a9315c.png)

Sanal Bilgisayarda kurulumu denedim ondada çalıştırırken aynı hatayı alıyorum.


Çalıştırmak için kullandığım komut : 

Python start.py 

aldığım hata

C:\Users\astra\Desktop\Camelishing-master>python start.py
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    from PyQt5.QtWidgets import QApplication , QMainWindow ,QFileDialog , QListWidget,QListWidgetItem ,QTreeWidgetItem ,QMessageBox,QLineEdit,QGraphicsPixmapItem
ImportError: DLL load failed: Belirtilen yordam bulunamadı.


Yardımınız için teşekkürler.

**Comment by cryptonic01** [comment]
Şuanda bütün gerekenleri yükledim ve hala aynı hatayı alıyorum. 

_**C:\WINDOWS\system32>cd C:\Users\astra\Desktop\Camelishing-master

C:\Users\astra\Desktop\Camelishing-master>pip install -r requirements.txt
Collecting PyQt5==5.11.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/84/44/32c311a6fb23b8b5cc4f535af1ad65fc3e071440884a1fad3c1aef68f47b/PyQt5-5.11.2-5.11.1-cp35.cp36.cp37.cp38-none-win32.whl
Collecting PyInstaller==3.3.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz
Collecting XlsxWriter==1.0.5 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/33/50/136b801d106fcebb2428a764e5c599e020d8227a3623db078e05eb4793a5/XlsxWriter-1.0.5-py2.py3-none-any.whl
Collecting matplotlib==2.2.2 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/7d/09/fc28652cb80c5ecec58aaee35274e9a4ffb07729e893ef8887428f2fe7bf/matplotlib-2.2.2-cp35-cp35m-win32.whl
Collecting openpyxl==2.5.4 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/f6/13/3c1263b852377738eaa60f99602fb58cc8ad2fd1badb0b724b0d5b532727/openpyxl-2.5.4.tar.gz
Collecting paramiko==2.4.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl
Collecting pywin32==223 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/32/0f/16419ffd63c60b0c197614c430eab35360a94154ac1b846b3ee69f8c8061/pywin32-223-cp35-cp35m-win32.whl
Collecting PyQt5_sip<4.20,>=4.19.11 (from PyQt5==5.11.2->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/68/44/8127dbace2809a66d51f0735a52721a4cb9b64ef6249ed14a0a126138b52/PyQt5_sip-4.19.12-cp35-none-win32.whl
Requirement already satisfied: setuptools in c:\program files (x86)\python 3.5\lib\site-packages (from PyInstaller==3.3.1->-r requirements.txt (line 2)) (18.2)
Collecting pefile>=2017.8.1 (from PyInstaller==3.3.1->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7e/9b/f99171190f04cd23768547dd34533b4016bd582842f53cd9fe9585a74c74/pefile-2017.11.5.tar.gz
Collecting macholib>=1.8 (from PyInstaller==3.3.1->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fd/89/58e160e4c3a010dd85dab1a43d20d4728be759fbffc1fc78356b344ffe98/macholib-1.9-py2.py3-none-any.whl
Collecting future (from PyInstaller==3.3.1->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting pypiwin32 (from PyInstaller==3.3.1->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/1b/f0/c90d0068665841f2a303480ae51c192363b46d2d3c78080cce926444623f/numpy-1.15.0-cp35-none-win32.whl
Collecting python-dateutil>=2.1 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib==2.2.2->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/0b/78/cab95f791d437bc2951ead6d7b4964b8cc578c149048161f49a6d8dfe336/kiwisolver-1.0.1-cp35-none-win32.whl
Collecting jdcal (from openpyxl==2.5.4->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/a0/38/dcf83532480f25284f3ef13f8ed63e03c58a65c9d3ba2a6a894ed9497207/jdcal-1.4-py2.py3-none-any.whl
Collecting et_xmlfile (from openpyxl==2.5.4->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Collecting pynacl>=1.0.1 (from paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/03/1b/23308246e369afdf826f8282d613ac11f1848758b33743e28dca423fb479/PyNaCl-1.2.1-cp35-cp35m-win32.whl
Collecting cryptography>=1.5 (from paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/fa/78/fe2c845554681de72edd9eb4e8385d1c79143f5c204a6af36f3f33c29777/cryptography-2.3-cp35-cp35m-win32.whl
Collecting pyasn1>=0.1.7 (from paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl
Collecting bcrypt>=3.1.3 (from paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a9/35/4a9409f7a92f4dc3de8d7ac8ccbdb8960a671f3379855c9b96a3e6912800/bcrypt-3.1.4-cp35-cp35m-win32.whl
Collecting altgraph>=0.15 (from macholib>=1.8->PyInstaller==3.3.1->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fe/fd/f63226be4aeebcac65d5f7e882bd00c8465ce883c1a4d16b18bd4ae9086e/altgraph-0.15-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ed/41/b91b33eae8f27238f0d7a58b2e27b93a09c59e179cff54b00938e28a20bc/cffi-1.11.5-cp35-cp35m-win32.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.5->paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko==2.4.1->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz
Installing collected packages: PyQt5-sip, PyQt5, future, pefile, altgraph, macholib, pywin32, pypiwin32, PyInstaller, XlsxWriter, numpy, six, python-dateutil, cycler, pytz, pyparsing, kiwisolver, matplotlib, jdcal, et-xmlfile, openpyxl, pycparser, cffi, pynacl, asn1crypto, idna, cryptography, pyasn1, bcrypt, paramiko
  Running setup.py install for future ... done
  Running setup.py install for pefile ... done
  Running setup.py install for PyInstaller ... done
  Running setup.py install for et-xmlfile ... done
  Running setup.py install for openpyxl ... done
  Running setup.py install for pycparser ... done
Successfully installed PyInstaller-3.3.1 PyQt5-5.11.2 PyQt5-sip-4.19.12 XlsxWriter-1.0.5 altgraph-0.15 asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 cryptography-2.3 cycler-0.10.0 et-xmlfile-1.0.1 future-0.16.0 idna-2.7 jdcal-1.4 kiwisolver-1.0.1 macholib-1.9 matplotlib-2.2.2 numpy-1.15.0 openpyxl-2.5.4 paramiko-2.4.1 pefile-2017.11.5 pyasn1-0.4.3 pycparser-2.18 pynacl-1.2.1 pyparsing-2.2.0 pypiwin32-223 python-dateutil-2.7.3 pytz-2018.5 pywin32-223 six-1.11.0

C:\Users\astra\Desktop\Camelishing-master>start.py
Traceback (most recent call last):
  File "C:\Users\astra\Desktop\Camelishing-master\start.py", line 4, in <module>
    from PyQt5.QtWidgets import QApplication , QMainWindow ,QFileDialog , QListWidget,QListWidgetItem ,QTreeWidgetItem ,QMessageBox,QLineEdit,QGraphicsPixmapItem
ImportError: No module named 'PyQt5'**_

**Comment by azizaltuntas** [comment]
Selamlar. Hangi python sürümünü kullanıyorsunuz ? Normal şartlarda kuruldu ise böyle bir hata vermemesi gerekir. Environment olayında pip hangi sürüm için kurulum yapmakta onları kontrol edermisin ?

**Comment by cryptonic01** [comment]
Python 3.4 sürümünü kullanıyorum ben normal olarak kurulum yapiyorum hatta bir cok defa silip denedim fakat gene ayni sekil python 3.5 surumunude denedim fakat gene ayni sekilde hata aliyorum. siz hangi python surumun oneriyorsununuz ? Ayrica Environment olayi derken anliyamadim ingilizcesi nedir acaba ?  😃

**Comment by azizaltuntas** [comment]
Ben 3.6 sürümünü kullanıyorum.pip3 install şeklinde kurmayı denermisin ?  Birde [https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk](url) buradaki linkten sdk yı kurun.Buda lazım olacaktır herzaman aklıma gelmişken söyleyeyim.Hatana gelince ben kurulum yaptım aynı şekilde dün tekrar bir hata ile karşılaşmadım.Ben tekrar bir araştırma yapıp döneceğim.

**Comment by cryptonic01** [comment]
Teşekkürler hemen deniyeceğim. Ben normal pip ile deniyordum pip3 ile hemen deniyeceğim şimdi.  Bende Windows SDK mevcut fakat bir eski sürümü onuda iyiki hatırlattınız update yapayım. Ayrıyetten Twitter de takip etme isteğimi kabul ederseniz sevinirim kullanıcı adım @cryptk01.

Türk'lerin böyle tooları geliştirmesi beni çok ve çok heyecanlandırıyor ve mutlu ediyor. verdiğiniz emeğe teşekkür ederim.

**Comment by azizaltuntas** [comment]
Ne demek rica ederim.Aktif kullanmıyorum girdiğimde kabul edeceğim :) Bir hata ile karşılaşırsanız söyleyin bazı ince detayları var çalışması için yardımcı olurum.Teşekkürler..

**Comment by cryptonic01** [comment]
Çok teşekkürler python 3.6 kurdum ve pip3 ile çalıştırmaya çalıştım çalıştı. teşekkür ederim. tabi her zaman karşılaşırsam hata ile sizi bildiririm.

**Comment by brandontict** [comment]
> Please try;

> sudo apt-get install python3-pyqt5
> sudo apt-get install qttools5-dev-tools
> sudo apt-get install qtcreator pyqt5-dev-tools
> pip3 install pyqt5

Above downloaded packages, still receiving error 

 `Couldnot find a version that satisfies the requirement PyQt5==5.11.2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for PyQt5==5.11.2 (from -r requirements.txt (line 1))` 

while running 
` pip install -r requirements.txt
`



Kali Linux 2018.2 . Updated weekly

**Comment by cryptonic01** [comment]
Well, thats good! Please Feel free to report the bugs and any other problems that you got or found  about the Camelishing Tool. Thanks.
